### ISSUE TITLE
Using multiple `@MorphMap('ALIAS')` causes ace to not resolve morphMap binding

### ISSUE THREAD

**Issue by josevelaz** [holoyan/adonisjs-permissions#20]
When running any ace commace, ie `node ace`, `node ace list`, etc, etc the following error occurs

```
RuntimeException: Cannot resolve binding "morphMap" from the container
    at createError (file:///Users/adonis-application/node_modules/@adonisjs/fold/build/chunk-IGHHTAHI.js:294:79)
    at ContainerResolver.resolveFor (file:///Users/adonis-application/node_modules/@adonisjs/fold/build/chunk-IGHHTAHI.js:375:11)
    at ContainerResolver.make (file:///Users/adonis-application/node_modules/@adonisjs/fold/build/chunk-IGHHTAHI.js:381:17)
    at Container.make (file:///Users/adonis-application/node_modules/@adonisjs/fold/build/chunk-IGHHTAHI.js:548:34)
    at service (file:///Users/adonis-application/node_modules/@holoyan/adonisjs-permissions/build/src/decorators.js:5:46)
    at file:///Users/adonis-application/node_modules/@holoyan/adonisjs-permissions/build/src/decorators.js:9:43
    at DecorateConstructor (/Users/adonis-application/node_modules/reflect-metadata/Reflect.js:549:33)
    at Reflect.decorate (/Users/adonis-application/node_modules/reflect-metadata/Reflect.js:143:24)
    at _ts_decorate (file:///Users/adonis-application/app/models/module.ts:3:92)
    at file:///Users/adonis-application/app/models/module.ts:45:10 {
  status: 500,
  code: 'E_RUNTIME_EXCEPTION'
```

After some debugging I noticed that if any other model besides the user model recieves a `@MorphMap` then it causes ace to crash.

I messed around with the configuration on `kernel.ts` and ace and no success

![CleanShot 2024-11-27 at 12 53 02](https://github.com/user-attachments/assets/be736e1b-c7bc-4afd-8f97-832d8a278af9)

**Comment by josevelaz** [comment]
No worries! Yes its still an issue. These are the versions

```
"@holoyan/adonisjs-permissions": "^1.0.3"
 "@adonisjs/core": "^6.13.1"
"@adonisjs/lucid": "^21.2.0"
```

**Comment by holoyan** [comment]
Hi @josevelaz , I couldn't reproduce this issue, but I can suggest to try registring morphs this way, maybe it will fix the issue

1. Create [provider](https://docs.adonisjs.com/guides/concepts/service-providers#writing-service-providers) if you don't have already
2. Register the model using this way
```typescript 

  /**
   * The container bindings have booted
   */
  async boot() {
    const morhpManager = await this.app.container.make('morphMap')
    morhpManager.set('users', User)
    // morhpManager.set('account', Account) // or whatever it is
  }

```

let me know if this fixed the issue.

btw do you use these models inside the commands?

**Comment by josevelaz** [comment]
@holoyan Doing this resulted in the error above being caused when starting the server.

> btw do you use these models inside the commands?
Not directly. I have a `Documents`model that has a relationship with `Module`. `Documents` is used inside a command.

After you mentioned this i removed the command that used the `Documents` model and ace works fine.

**Comment by holoyan** [comment]
@josevelaz  by deault inside the [command](https://gitlab.com/TeamScanblox/API/-/merge_requests/1417/diffs)  (options.startApp section) application is not booted, because of that this issue can happen. If you are planing to use models inside the commands, please don't forget to start the app.


Let me know if you have any question

**Comment by josevelaz** [comment]
@holoyan I had already tried that and it did not work, just retried it and still the issue is occuring 😔

**Comment by holoyan** [comment]
@josevelaz can you please create public repo where this issue is reproducable?, so I can take close look

**Comment by josevelaz** [comment]
@holoyan Here is a minimal [reproduction repo ](https://github.com/josevelaz/adonis-permissions-morph-map-test).

**Comment by holoyan** [comment]
Hi @josevelaz  thanks for sharing the repo, seems that even though `startApp` is `true` still some dependencies is not can't be found.

But when you use service provider and register in it, everything works fine, please check this PR, it's a working example and tested


https://github.com/josevelaz/adonis-permissions-morph-map-test/pull/1/files

**Comment by josevelaz** [comment]
Awesome, thank you. 
Any idea what the root cause of this issue could be?

**Comment by holoyan** [comment]
>Any idea what the root cause of this issue could be?

Not sure fully but my assumption is that when you run the command it tries to "load" models and related relations, and during this time app is not booted yet and `permission` is not regeisterd, because of that it can't find module, will investigate further.

To run localy you need to clone package, install dependencies.
Then to install localy inside your adonisjs project you can use [yalc](https://github.com/wclr/yalc).

As a reference you can use this [tutorial](https://artaksafaryanc.medium.com/adonisjs-v6-package-development-part-1-34c714c0ab9a) I've created, there is an example on how to run locally.

>There's a few ideas I'd like to contribute whenever I have the time

Sure @josevelaz , all new ideas are welcomed

**Comment by sayeed205** [comment]
Do I still need to create a provider and use the model morph map in the boot 
or this issue is fixed?

I have a command that uses `Acl.model(user).assignRole(this.role!)` and I am getting same error as mentioned in the issue tittle.

**Comment by holoyan** [comment]
Hi @sayeed205 , 

Yes please create a provider, most probably on the next release it will be resolved

**Comment by holoyan** [comment]
Hi @sayeed205 [new version ](https://github.com/holoyan/adonisjs-permissions?tab=readme-ov-file#release-notes) was released and this issue should be fixed.

**Comment by sayeed205** [comment]
GG 👍 thanks
